'email': 'INSERT ROGERS USERNAME HERE'
'password' : 'INSERT ROGERS PASSWORD HERE'
'twilio-accountSID' : 'INSERT TWILIO ACCOUNT SID HERE'
'twilio-authToken' : 'INSERT TWILIO AUTH TOKEN HERE'
'fromNumber' : 'INSERT TWILIO PHONE NUMBER HERE'
'toNumber' : 'INSERT YOUR PERSONAL PHONE NUMBER HERE'
